export enum Pathes {
  AUTH = '/auth',
  MAIN = '/',
  VERIFY = '/auth/verify',
  SUPPORT = '/support',
  POLICY = '/policy',
  TERMS = '/terms',
  TO_BUY = '/to-buy',
  MENU_LIST = '/menu-list',
  ACCOUNT = '/account',
  AI_CHAT = '/ai-chat',
  FALLBACK = '/fallback',
  ABOUT = '/about',
  WEB_CAM = '/cam',
  PROMO = '/promo',
  INSTALL = '/install',
  GIFTS = '/gifts',
  PROMO_FEAR = '/promo-fear',
};